version: '3'

services:
  app:
    container_name: portfolio-php
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - 8080:80
    networks:
      - portfolio
    env_file:
      - .env

networks: 
  portfolio:
    driver: bridge